-- schema.sql
CREATE TABLE IF NOT EXISTS rooms (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    names TEXT NOT NULL,
    songs TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS youtubeLinks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT NOT NULL,
    playlistId TEXT NOT NULL
);


